#!/usr/bin/env bash

set -e

source '.installer/utilities.lib.sh'
source '.installer/dotbot.lib.sh'
source '.installer/python.lib.sh'

#CONFIG="install.conf.yaml"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

_install_via_dotbot $BASEDIR 