#!/usr/bin/env bash

SCRIPT_PATH="$(dirname $0)"

source "${SCRIPT_PATH}/.installer/lib/path.lib.sh"
source "${SCRIPT_PATH}/.installer/lib/logging.lib.sh"
source "${SCRIPT_PATH}/.installer/lib/install.lib.sh"

SHELLRC_PATH=${SHELLRC_PATH:-~/.shellrc}

mkdir -p "${HOME}/.shellrc/local.d" "${HOME}/bin" "${HOME}/.shellrc/plugins"

# Clean up broken symlinks
find "${HOME}" -maxdepth 1 -xtype l -delete

cd "${SHELLRC_PATH}"

link_file "dotfiles/bin" "bin"

declare -a paths=("init" "init.d" "login.d" "platform.d" "shell.conf.d" "shellrc.d" )

for path in "${paths[@]}"; do
  link_file "dotfiles/init/${path}" "${path}"
done

cd "${HOME}"

declare -A DOTMAP=(
  [.bashrc]=files/bash/bashrc
  [.bash_profile]=files/bash/bash_profile
  [.zshrc]=files/zsh/zshrc
  [.vimrc]=files/vim/vimrc
  [.tmux.conf]=files/tmux/tmux.conf
  [.tmuxrc]=files/tmux/tmuxrc
) 

for file in "${!DOTMAP[@]}"; do
  DOTFILE="${SHELLRC_PATH}/dotfiles/${DOTMAP[$file]}"
  DOTFILE=$(real_to_abspath "${HOME}" "${DOTFILE}")
  link_file "${DOTFILE}" "${file}"
done

cd "${HOME}/.shellrc/plugins"

# Installing plugins is uglier. I don't have a "real" fix for this yet.
declare -a PLUGINS=(
  fasd
  pathpicker
  fzf
)

for plugin in "${PLUGINS[@]}"; do
  if [[ -e "../dotfiles/files/plugins/${plugin}" ]]; then
    link_file "../dotfiles/files/plugins/${plugin}" "${plugin}"
  fi
done
