#!/usr/bin/env bash

SCRIPT_PATH="$(dirname $0)"

source "${SCRIPT_PATH}/.installer/lib/path.lib.sh"
source "${SCRIPT_PATH}/.installer/lib/logging.lib.sh"
source "${SCRIPT_PATH}/.installer/lib/install.lib.sh"

SHELLRC_PATH=${SHELLRC_PATH:-~/.shellrc}

while [[ $# -gt 0 ]]; do 
  case $1 in 
    -y|--yes) 
      overwrite_all="true" 
      shift 
      ;; 
  esac 
done

mkdir -p "${HOME}/.shellrc/local.d" "${HOME}/bin" "${HOME}/.shellrc/plugins"

# Clean up broken symlinks
find "${HOME}" -maxdepth 1 -type l -exec test ! -e {} \; -print

cd "${SHELLRC_PATH}"

link_file "dotfiles/bin" "bin"

declare -a paths=("init" "init.d" "login.d" "platform.d" "shell.conf.d" "shellrc.d" )

for path in "${paths[@]}"; do
  link_file "dotfiles/init/${path}" "${path}"
done

cd "${HOME}"

declare -a DOTMAP=(
  ".bashrc=files/bash/bashrc"
  ".bash_profile=files/bash/bash_profile"
  ".zshrc=files/zsh/zshrc"
  ".vimrc=files/vim/vimrc"
  ".tmux.conf=files/tmux/tmux.conf"
  ".tmuxrc=files/tmux/tmuxrc"
)

for filemap in "${DOTMAP[@]}"; do
  DEST="${filemap%%=*}"
  SRC="${filemap#*=}"
  DOTFILE="${SHELLRC_PATH}/dotfiles/${SRC}"
  DOTFILE=$(real_to_abspath "${HOME}" "${DOTFILE}")
	link_file "${DOTFILE}" "${DEST}"
done

cd "${HOME}/.shellrc/plugins"

# Installing plugins is uglier. I don't have a "real" fix for this yet.
declare -a PLUGINS=(
  fasd
  pathpicker
  fzf
)

for plugin in "${PLUGINS[@]}"; do
  if [[ -e "../dotfiles/files/plugins/${plugin}" ]]; then
    link_file "../dotfiles/files/plugins/${plugin}" "${plugin}"
  fi
done
