#!/usr/bin/env bash

# Do nothing if we're not on something Debian-based
[[ -f /etc/debian_version ]] || exit 0

if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

apt-get update

cat <<-__PACKAGES__  | xargs apt-get -ym install
ack
glances
htop
iftop
iotop
iptraf
jq
lnav
mc
moreutils
ncdu
peco
ranger
rename
rsync
silversearcher-ag
tmux
urlview
__PACKAGES__

