# ~/.bashrc: executed by bash(1) for non-login shells.

if [[ $- != *i* ]] ; then
  # shell is non-interactive. be done now!
  return
fi

source $HOME/.shellrc/init

for _shell_path in shellrc.d login.d local.d "platform.d/${OSTYPE}"; do
    _load_shellrc_path $_shell_path
done
