#!/usr/bin/env sh

_maximize_pane() {
  local current_session=${1:-$(tmux display -p '#{session_name}')} #'
  local current_pane=${2:-$(tmux display -p '#{pane_id}')}         #'

  local dead_panes=$(tmux list-panes -s -t "$current_session" -F '#{pane_dead} #{pane_id} #{pane_start_command}' | grep -o '^1 %.\+maximized.\+$' || true)
  local restore=$(echo "$dead_panes" | sed -n -E -e "s/^1 $current_pane .+maximized.+'(%[0-9]+)'$/tmux swap-pane -s \1 -t $current_pane \; kill-pane -t $current_pane/p" -e "s/^1 (%[0-9]+) .+maximized.+'$current_pane'$/tmux swap-pane -s \1 -t $current_pane \; kill-pane -t \1/p")

  if [ -z "$restore" ]; then
    [ "$(tmux list-panes -t "$current_session:" | wc -l | sed 's/^ *//g')" -eq 1 ] && tmux display "Can't maximize with only one pane" && return
    local window=$(tmux new-window -t "$current_session:" -P "exec maximized... 2> /dev/null & tmux setw -t \"$current_session:\" remain-on-exit on; printf \"Pane has been maximized, press <prefix>+ to restore. %s\" '$current_pane'")
    window=${window%.*}

    local guard=10
    while [ x"$(tmux list-panes -t "$window" -F '#{session_name}:#{window_index} #{pane_dead}' 2>/dev/null)" != x"$window 1" ] && [ "$guard" -ne 0 ]; do
      sleep 0.01
      guard=$((guard - 1))
    done
    if [ "$guard" -eq 0 ]; then
      tmux display 'Unable to maximize pane'
    fi

    new_pane=$(tmux display -t "$window" -p '#{pane_id}')
    tmux setw -t "$window" remain-on-exit off \; swap-pane -s "$current_pane" -t "$new_pane"
  else
    $restore || tmux kill-pane
  fi
}

_fpp() {
  tmux capture-pane -J -S - -E - -b "fpp-$1" -t "$1"

  tmux split-window "tmux show-buffer -b fpp-$1 | fpp || true; tmux delete-buffer -b fpp-$1"
}

_show_bindings() {
  tmux split-window 'tmux list-keys | sed -e "s/^bind-key.*[-]T\s\(root\|prefix\|copy-mode\)/\1/" | sort | cut -c-$COLUMNS | less'
}

_split_window() {
  local tty=${1:-$(tmux display -p '#{pane_tty}')} #'
  shift
  # shellcheck disable=SC2039
  if [ x"$OSTYPE" = x"cygwin" ]; then
    local pid=$(ps -a | sort -d | awk -v tty="${tty##/dev/}" '$5 == tty && /ssh/ && !/-W/ { print $1; exit 0 }')
    [ -n "$pid" ] && ssh=$(tr '\0' ' ' <"/proc/$pid/cmdline")
  else
    local ssh=$(ps -t "$tty" -o command= | sort -d | awk '/ssh/ && !/-W/ { print $0; exit 0 }')
  fi
  if [ -n "$ssh" ]; then
    # shellcheck disable=SC2046
    tmux split-window "$@" $(echo "$ssh" | sed -e "s/;/\\\\;/g")
  else
    tmux split-window "$@"
  fi
}

_toggle_mouse() {
  local old=$(tmux show -gv mouse)
  local new=""

  if [ "$old" = "on" ]; then
    new="off"
  else
    new="on"
  fi

  tmux set -g mouse $new \; \
    display "mouse: $new"
}

_edit_printscreen() {
  local PANE=$1
  local BUFFER_TEMPFILE="$(mktemp)"
  local PRINTSCREEN_EDITOR="${EDITOR:-vi}"

  if [ ! -z "$PANE" ]; then
    tmux capture-pane -t "$pane" -S -32768 -p >"${BUFFER_TEMPFILE}"
  else
    tmux capture-pane -S -32768 -p >"${BUFFER_TEMPFILE}"
  fi

  tmux display "$buffer_tempfile"

  tmux new-window -n "PRINTSCREEN" "${PRINTSCREEN_EDITOR} ${BUFFER_TEMPFILE}; rm ${BUFFER_TEMPFILE}"
}

"$@"
